const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

const eyeColors = ['Amber', 'Blue', 'Brown', 'Gray', 'Green', 'Hazel', 'Red', 'Violet'];

const hairColors = ['Black', 'Blonde', 'Brown', 'Red', 'White', 'Gray', 'Blue', 'Green', 'Purple'];

const hairTypes = ['Straight', 'Wavy', 'Curly', 'Kinky'];

const universities = [
  'Princeton University',
  'Harvard University',
  'Columbia University',
  'Massachusetts Institute of Technology (MIT)',
  'Yale University',
  'Stanford University',
  'University of Chicago',
  'University of Pennsylvania',
  'California Institute of Technology (Caltech)',
  'Johns Hopkins University',
  'Northwestern University',
  'Duke University',
  'Dartmouth College',
  'Brown University',
  'Vanderbilt University',
  'Rice University',
  'Washington University in St. Louis',
  'Cornell University',
  'University of Notre Dame',
  'University of California--Berkeley',
  'University of California--Los Angeles (UCLA)',
  'Emory University',
  'University of Southern California',
  'Georgetown University',
  'University of Michigan--Ann Arbor',
  'Carnegie Mellon University',
  'University of Virginia',
  'Wake Forest University',
  'New York University (NYU)',
  'University of California--Santa Barbara',
  'University of Florida',
  'University of Rochester',
  'Tufts University',
  'University of California--San Diego',
  'Boston College',
  'University of North Carolina--Chapel Hill',
  'University of California--Irvine',
  'University of Wisconsin--Madison',
  'University of Texas--Austin',
  'Boston University',
  'University of Illinois--Urbana-Champaign',
  'William & Mary',
  'Northeastern University',
  'Pepperdine University',
  'Ohio State University',
  'University of Miami',
  'Syracuse University',
  'Purdue University',
  'University of Connecticut',
];

const banks = [
  'Industrial and Commercial Bank of China (ICBC)',
  'China Construction Bank Corporation (CCB)',
  'Agricultural Bank of China (ABC)',
  'Bank of China (BOC)',
  'Mitsubishi UFJ Financial Group (MUFG)',
  'JPMorgan Chase & Co.',
  'HSBC Holdings plc',
  'BNP Paribas',
  'Bank of America Corporation',
  'Wells Fargo & Co.',
  'Citigroup Inc.',
  'Sumitomo Mitsui Financial Group (SMFG)',
  'Mizuho Financial Group',
  'Banco Santander',
  'The Goldman Sachs Group, Inc.',
  'Barclays plc',
  'Morgan Stanley',
  'Royal Bank of Canada (RBC)',
  'UBS Group AG',
  'The Toronto-Dominion Bank (TD Bank)',
];

const cardTypes = [
  'Visa',
  'Mastercard',
  'American Express',
  'Discover',
  'UnionPay',
  'JCB',
  'Diners Club International',
  'Maestro',
  'RuPay',
  'Mir',
  'Elo',
  'BC Card',
  'Carte Bancaire',
  'Interac',
  'NPS',
  'Korean Express',
  'RuPay International',
];

const currencyCodes = ['USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CNY', 'SEK', 'NZD', 'TRY', 'PKR', 'INR', 'BRL'];

const userAgents = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
];

const countryCodes = ['+1', '+44', '+92', '+91', '+61', '+81', '+49'];

const streetNames = [
  'Main Street',
  'First Street',
  'Second Street',
  'Third Street',
  'Fourth Street',
  'Fifth Street',
  'Sixth Street',
  'Seventh Street',
  'Eighth Street',
  'Ninth Street',
  'Tenth Street',
  'Elm Street',
  'Oak Street',
  'Pine Street',
  'Maple Street',
  'Cedar Street',
  'Washington Street',
  'Lincoln Street',
  'Jefferson Street',
  'Madison Street',
  'Adams Street',
];

const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'Indianapolis',
  'San Francisco',
  'Seattle',
  'Denver',
  'Washington',
];

const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

const stateCodesDic = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

const departments = [
  'Accounting',
  'Business Development',
  'Engineering',
  'Human Resources',
  'Legal',
  'Marketing',
  'Product Management',
  'Research and Development',
  'Sales',
  'Services',
  'Support',
  'Training',
];

const companies = [
  'Hand Group',
  'Bernier, Wolff and Windler',
  'Swift and Sons',
  'Lang and Sons',
  'Weber - Bradtke',
  'Marvin - Welch',
  'Keebler LLC',
  'Hilpert Inc',
  'Zulauf and Sons',
  'Upton Group',
  'Herzog Inc',
  'Pfannerstill Inc',
  'Lowe - Nader',
  'Langosh - Maggio',
  'Gerhold - Wintheiser',
  'Marvin Inc',
  'Auer, Beer and Durgan',
  'Stokes - Harber',
  'Johnson and Sons',
  'Rempel Inc',
  'Prosacco and Sons',
  'Stark Group',
  'Thompson Group',
  'Dibbert Group',
  'Mayer and Sons',
  'Harris - Klocko',
  'Nolan Group',
  'Nikolaus - Boyer',
  'Stokes - Konopelski',
  'Kiehn and Sons',
  'Grant, Jacobson and Ankunding',
  'Stark and Sons',
  'Shields and Sons',
  'Cassin Group',
  'Cremin - Koepp',
  'Altenwerth - Runolfsson',
  'Larkin, Towne and Wintheiser',
  'Pollich - Hilpert',
  'Mueller, Lemke and Stroman',
  'Fahey Group',
  'Krajcik Group',
  'Lehner - Veum',
  'Quitzon LLC',
  'Swaniawski and Sons',
  'Kessler, Kozey and Simonis',
  'Douglas, Larkin and Parker',
  'Kreiger - Parker',
  'Botsford, Marquardt and Roberts',
  'Hilll LLC',
  'Hickle, Altenwerth and Stamm',
  'Pagac Inc',
  'Windler - Douglas',
  'Sawayn, Koss and Medhurst',
  'Hintz Inc',
  'Waters, Ankunding and Green',
  'Kshlerin, Mitchell and Wilderman',
  'Bechtelar LLC',
  'Gibson - Greenholt',
  'Swift - Stamm',
  'Schmeler - Spinka',
  'Collier, Swaniawski and Sipes',
  'Dickens Group',
  'Leffler, Rolfson and Becker',
  'Wolf LLC',
  'Gorczany, King and Jenkins',
  'Aufderhar - Cormier',
  'Wisozk, Schamberger and Huels',
  'Vandervort Group',
  'Bradtke Group',
  'Oberbrunner LLC',
  'Shields Group',
  'Huels Group',
  'Romaguera - Hartmann',
  'Satterfield, Shields and Littel',
  'Langworth Group',
  'Feest Inc',
  'Pfeffer - Homenick',
  'Tromp, Gaylord and Weber',
  'Cremin Inc',
  'Blick and Sons',
  'Balistreri and Sons',
  'Runolfsson, Kohler and Welch',
  'Dickens - Beahan',
  'Bruen, Rau and Armstrong',
  'McCullough - Huel',
  'Mann, Ortiz and Mraz',
  'Quigley, Dare and Kovacek',
  'Stokes, Koch and Kozey',
  'Schaefer, Hackett and Kreiger',
  'Goldner, Batz and Hilpert',
  'Kuhic, Wintheiser and Prohaska',
  'Jacobi - Miller',
  'Botsford Inc',
  'Gutmann - Von',
  'Von Inc',
  'Dooley, Kozey and Cronin',
  'Koelpin Inc',
  'Lehner, Wisozk and Vandervort',
  'Hilpert Inc',
  'Homenick and Sons',
  'Reilly, Shields and Spinka',
  'Prohaska - Thiel',
  'Rosenbaum, Krajcik and Lesch',
  'Dickens, Tremblay and Quigley',
  'Heller LLC',
  'Predovic - Johns',
  'Kunde and Sons',
  'Gutkowski and Sons',
  'Hudson, Buckridge and Greenholt',
  'Stanton - Weissnat',
  'Stiedemann LLC',
  'King, Swift and Schroeder',
  'Steuber - Ledner',
  'Mertz, Conn and Zulauf',
  'Fadel Inc',
  'Cronin, Thiel and Labadie',
  'Nienow - Fritsch',
  'Carroll, Kuphal and Durgan',
  'Erdman Inc',
  'Will, Stamm and Zieme',
  'Treutel LLC',
  'Koelpin - Reinger',
  'Luettgen and Sons',
  'Daugherty - Kilback',
  'Halvorson LLC',
  'Mohr - Hessel',
  'Berge - Gleason',
  'Tremblay - Simonis',
  'Schmitt, Beahan and Hermann',
  'Weber Inc',
  'Ziemann - Rau',
  'Blanda - Jacobson',
  'Roberts LLC',
  'Grant, Kassulke and McGlynn',
  'Ledner and Sons',
  'Pollich, Dickinson and Thompson',
  'Zemlak - Schmidt',
  'Sanford and Sons',
  'Considine, Stiedemann and Doyle',
  'Jast - Nader',
  'Lebsack Inc',
  'Weissnat, Wyman and Turner',
  'Durgan - Marks',
  'Green and Sons',
  'Will, Haag and Reichel',
  'Jacobs - Nader',
  'Parker Inc',
  'Stoltenberg - Nienow',
  'Bradtke - Hoeger',
  'Koelpin - Lowe',
  'Fahey - Bashirian',
  'Feil, Wolff and Gibson',
  'Marks, McDermott and Goodwin',
  'Padberg Group',
  'Spencer - Adams',
  'Kuhic and Sons',
  'Okuneva Group',
  'Pfannerstill Inc',
  'Nikolaus Inc',
  'Windler, Hayes and Runolfsdottir',
  'Hartmann, Hilpert and Kulas',
  'Kreiger Inc',
  'Von Inc',
  'Larson Inc',
  'Adams - McLaughlin',
  'Mayer - Smitham',
  'Kihn - Thompson',
  'Pacocha Inc',
  'Ullrich LLC',
  'Kihn - Goldner',
  'Emmerich, Kuhlman and Torp',
  'Morissette, Baumbach and Auer',
  'Zieme, Effertz and Hahn',
  'Stiedemann - Wolf',
  'Gorczany - Gottlieb',
  'Abbott and Sons',
  'Miller, Schowalter and Wisozk',
  'Mante LLC',
  'Kohler and Sons',
  'Ankunding, Little and Flatley',
  'Crona, Grant and Hodkiewicz',
  'Walsh, Gutmann and Ortiz',
  'Dickinson, Connelly and Sporer',
  'Sauer, Ernser and Gusikowski',
  'Greenfelder - Bauch',
  'Schmidt - Hyatt',
  'Schumm, Bartell and McKenzie',
  'Considine - Torp',
  'Koch, Lind and Keebler',
  'Lueilwitz Inc',
  'Sipes, Bailey and Daniel',
  'Armstrong Inc',
  'Cruickshank LLC',
  'Roberts LLC',
  'Bashirian Group',
  'Marks LLC',
  'Dooley LLC',
  'Aufderhar LLC',
  'Schiller - Zieme',
  'Mayer, Spinka and Schmitt',
  'Gislason Group',
  'Schowalter Group',
  'Cassin Group',
  'Keebler and Sons',
  'Ritchie and Sons',
  'King - Muller',
  'Gusikowski - Toy',
  'Moore Inc',
  'Bailey, Franecki and West',
  'Ernser Group',
  'Bruen - Yundt',
  'Bruen and Sons',
  'Barton - Schultz',
  'Kub, Jacobs and Collier',
  'Wuckert Group',
  'Feeney LLC',
  'Auer, Carter and Wintheiser',
  'Gibson LLC',
  'West, Jast and Balistreri',
  'Watsica and Sons',
  'Gerlach, Funk and Schoen',
  'Jaskolski - McLaughlin',
  'Price and Sons',
  'Barton, Blick and Osinski',
  'Ruecker - Davis',
  'Wisoky - Rowe',
  'Hudson - Marquardt',
  'Kreiger and Sons',
  'Considine, Heathcote and Abernathy',
  'Kuhic, Romaguera and Funk',
  'Wisozk - Feeney',
  'Brown, McLaughlin and Koelpin',
  'Spinka LLC',
  'Kutch Group',
  'Auer, Hettinger and Bradtke',
  'Grady LLC',
  'Hilpert and Sons',
  'Spinka - Dickinson',
  'Kuhlman LLC',
  'Bogan Inc',
  'Ward - Sauer',
  'Nicolas, Adams and West',
  'Price - Kuhic',
  'Rippin Inc',
  'Strosin, Anderson and Baumbach',
  'Daniel - Schimmel',
  'Graham - Gulgowski',
  'Kling Inc',
  'Hudson, Labadie and Greenfelder',
  'West, Borer and Heaney',
  'Oberbrunner, Mosciski and Witting',
  'Berge, Reinger and Oberbrunner',
  'Kulas - Littel',
  'Beatty Inc',
  'Pagac and Sons',
  'Abernathy, Muller and Hintz',
  'Hahn - Lakin',
];

const titles = [
  'Accountant',
  'Business Analyst',
  'Business Development Manager',
  'Chief Executive Officer',
  'Chief Financial Officer',
  'Chief Information Officer',
  'Chief Operating Officer',
  'Chief Technology Officer',
  'Data Analyst',
  'Data Scientist',
  'Database Administrator',
  'Developer',
  'Engineer',
  'Human Resources Manager',
  'Legal Counsel',
  'Marketing Manager',
  'Product Manager',
  'Project Manager',
  'Quality Assurance Engineer',
  'Research Analyst',
  'Sales Manager',
  'Software Architect',
  'Software Engineer',
  'Support Specialist',
  'Systems Analyst',
  'Technical Support Engineer',
  'Web Developer',
];

module.exports = {
  bloodGroups,
  eyeColors,
  hairColors,
  hairTypes,
  universities,
  banks,
  cardTypes,
  currencyCodes,
  userAgents,
  countryCodes,
  streetNames,
  cities,
  states,
  stateCodesDic,
  departments,
  companies,
  titles,
};
